apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-add-tasks-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-add-tasks-api
  template:
    metadata:
      labels:
        app: todo-add-tasks-api
    spec:
      containers:
      - name: todo-add-tasks-api
        image: prodacrk8s01.azurecr.io/todo-add-tasks-api:v1
        ports:
        - containerPort: 8000
        env: 
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:prodsqlk8s01.database.windows.net,1433;Database=sqlavengersdb001;Uid=sqladminuser;Pwd=Sql@12345678;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"        
